on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main

name: Test
jobs:
  test:
    name: Units
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Units
        env:
          # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#xcode
          XCODE_PATH: "/Applications/Xcode_11.5.app"
        run: rake test
